### PR TITLE
Online filter

### PR DESCRIPTION
**Pull request by taigercub**
Fixed functionality of pre-requisit check box and added online only check box with functionality

### CODE REVIEW

**Review by dtlemon — APPROVED** [review]
Like Owen, definitely going to have to handle merge conflicts. Pre-req works on current version of main and you don't have a go button, so make sure those don't get messed up when you commit

**Comment by Peyton3995** [comment]
How removing over 27,000 lines of code and adding over 17,000. This is not a critique, and it is okay if you do not have the answer, but I am genuinely curious.

**Comment by taigercub** [comment]
I am honestly not sure either, I think it was prettier but I am not sure

**Comment by Peyton3995** [comment]
Please update this to master

**Pull request closed without merging**
