### PR TITLE
Add department filter

### PR DESCRIPTION
**Pull request by jepoorbaugh**
This adds functionality to the Department Filter option.

### CODE REVIEW

**Review by Peyton3995 — COMMENTED** [review]
Very nicely done!

**Review by owenmock22 — COMMENTED** [review]
Pull main down and merge it into this and then I can approve it

**Comment by jepoorbaugh** [comment]
> Pull main down and merge it into this and then I can approve it

Hey Owen, Github isn't showing me that there's any merge conflicts. Am I missing something?

**Review by dtlemon — APPROVED** [review]

**Review by Peyton3995 — COMMENTED** [review]
Looks good!

**Review by Peyton3995 — APPROVED** [review]

**Pull request merged**
