### PR TITLE
Add online class filter

### PR DESCRIPTION
**Pull request by KedricNees01**

### CODE REVIEW

**Review by Mason-Wallace — COMMENTED** [review]
When testing it on my local computer The button on the screen appears, but when clicking on the items it does nothing. I also did a website preview and on inspecting the page I got this error (index):21 Uncaught ReferenceError: filterOnline is not defined
    at HTMLButtonElement.onclick ((index):21:69).

**Comment by Caburke1218** [comment]
Yeah same thing as Mason is saying also, the merge conflicts you are having I believe what you need to do is go to your local main branch and pull the new changes and merge your local main branch with your feature branch. Currently you are conflicting with Skylar's, marcus's and my merges.

**Review by Mason-Wallace — APPROVED** [review]
I pulled it to my branch and it worked.

**Review by Mason-Wallace — COMMENTED** [review]
Use npm Prettier to fix Issue.

**Review by Caburke1218 — APPROVED** [review]

**Pull request merged**
