### PR TITLE
Adds sort by course name

### PR DESCRIPTION
**Pull request by owenmock22**
Button will need moved into proper location but this allows the form to be sorted by the course column of the table

### CODE REVIEW

**Comment by dtlemon** [comment]
Need to look at merge conflicts, sort buttons don't work for what's already in main

**Comment by dtlemon** [comment]
Button is there but does nothing when I click on it

**Comment by owenmock22** [comment]
> Button is there but does nothing when I click on it

Definitely some issues with this.  I have fixed a few but need to work through a few more

**Review by Peyton3995 — APPROVED** [review]
So you do this in class, and saw the code work for myself. Approved. Nicely done.

**Review by AndrewG2026 — APPROVED** [review]
looks good. should fix enrolled sort and allow sort by course name

**Pull request merged**
