### PR TITLE
Added Availiability Toggle Button

### PR DESCRIPTION
**Pull request by Mackerell-Baka**

### CODE REVIEW

**Comment by jdspires00** [comment]
The code looks good and works properly, there are still a few things left to do. 1. You need to pull the most recent version of the code and merge your code into it. You can do that by choosing 'Pull, Push', 'pull from', and selecting 'origin/main'. and 2. You need to run prettier which I'll attach the code to run it below. 
Prettier code:
npm run lint-fix

**Comment by Mrcarroll66** [comment]
Pull the recent changes and run lint-fix and I'll approve this

**Comment by Mackerell-Baka** [comment]
Done.

**Comment by empaarlberg** [comment]
remove the changes outside of main and index and Ill approve it

**Review by empaarlberg — APPROVED** [review]
Just please remove the prettier files but Ill approve so you can merge whenver, watch out though because my merge changed a lot

**Pull request closed without merging**
