### PR TITLE
Start time

### PR DESCRIPTION
**Pull request by Peyton3995**
Adds the ability to filter the table by class start time.

### CODE REVIEW

**Review by owenmock22 — CHANGES_REQUESTED** [review]
Looks great other than you need to add in the time columns

**Comment by jepoorbaugh** [comment]
> Looks great other than you need to add in the time columns

I'm working on this change in a separate branch (#127)

**Review by owenmock22 — APPROVED** [review]
This looks good other than the columns need added.  I now know Ethan is doing that in a separate branch so this is good to merge.

**Review by jepoorbaugh — APPROVED** [review]
Lookin' good!

**Pull request merged**
