### PR TITLE
Add button to execute filters

### PR DESCRIPTION
**Pull request by jepoorbaugh**
This will add a button to execute the filters.

### CODE REVIEW

**Comment by jepoorbaugh** [comment]
> When I run this I don't see any of the courses pop up
Ah, there was a bug. It should be fixed now.

**Review by owenmock22 — APPROVED** [review]
Now that you have made changes after Dylan's comment this looks good and worked for me.

**Review by JIckes12 — APPROVED** [review]
This also looked good and worked properly for me after the changes.

**Review by Peyton3995 — APPROVED** [review]
I think it comes high time to merge this.

**Pull request merged**
